### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by J-J-Chiarella** [HarikalarKutusu/cv-tbox-dataset-analyzer#44]
Take a look at the dataset analyzer in any language, in any version.

E.g.: https://cv-dataset-analyzer.netlify.app/examine/en/12.0

Go to the “REPORTED” tab.

Go to the very bottom for “Reporting Reasons.”

The second column says “Grammer or Spelling.”

As ironic and funny as that is, I have to report this. It should be “Grammar or Spelling.”

**Comment by HarikalarKutusu** [comment]
Thank you :)

The irony is, the original code reads:
```
"bins_reasons.grammar-or-spelling": "Grammer or Spelling",
```

Fixed for the next release.

**Comment by HarikalarKutusu** [comment]
Fixed with #45
